name: Node.js Package

on:
  push:
    branches:
      - develop

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@ikuretechsoft"
      - run: npm install
      - run: tsc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
