name: CD Pipeline

on:
  workflow_run:
    workflows: ["Publish to docker hub"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull snrakshith/csh-svc-node:latest
      - name: Delete Old docker container
        run: sudo docker rm -f csh-svc-node-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 4000:4000 --name csh-svc-node-container snrakshith/csh-svc-node
