name: CD Pipeline

on:
  workflow_run:
    workflows: ["Publish Docker Image to public ECR"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull public.ecr.aws/a6v4j4g1/csh-svc-node:dev-${{ github.sha }}
      - name: Delete Old docker container
        run: sudo docker rm -f svc-container || true
      - name: Run Docker Container
        run: sudo docker run -idt -p 3000:4000 --name svc-container public.ecr.aws/a6v4j4g1/csh-svc-node:dev-${{ github.sha }}
