version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@2020
    volumes:
      - ./mongodb:/data/db