import createClient from "openapi-fetch";
import type { paths } from "./api/v1.ts"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://myapi.dev/v1/" });

const {
  response,
  data, // only present if 2XX response
  error, // only present if 4XX or 5XX response
} = await client.GET("/crm/companies", {
  params: {
    query: { cursor: "" },
    header: {
      "x-apideck-app-id": "",
      "x-apideck-consumer-id": "",
    },
  },
});

await client.POST("/crm/users", {
  params: {
    header: {
      "x-apideck-app-id": "",
      "x-apideck-consumer-id": "",
    },
  },
  body: {
    username: "",
    emails: [{ email: "sn", id: "1", type: "billing" }],
    department: "R&D",
  },
});
