apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: csh-acc
  namespace: argocd
spec:
  project: gitops-demo
  source:
    repoURL: https://github.com/snrakshith/csh-svc-node.git
    targetRevision: HEAD
    path: k8
  destination:
    server: https://kubernetes.default.svc
    namespace: akuity
