version: "3.7"
services:
  redis:
    image: redis:3.2.12
    container_name: redis-aof
    restart: always
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data/
volumes:
  redis_data: