name: ECR Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Update with your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 681873342152.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t 681873342152.dkr.ecr.ap-south-1.amazonaws.com/csh-svc:latest .
          docker push 681873342152.dkr.ecr.ap-south-1.amazonaws.com/csh-svc:latest

      - name: Logout from Amazon ECR
        run: docker logout 681873342152.dkr.ecr.ap-south-1.amazonaws.com

      - name: Run Docker container
        run: docker run -d -p 4000:4000 --name app-container 681873342152.dkr.ecr.ap-south-1.amazonaws.com/csh-svc:latest
