version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env    
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app:ro
      - ./usr/src/app/node_modules
    command: [ "npm", "run", "dev" ]
