version: "3.7"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.cnf
      - ./conf.d/:/etc/nginx/conf.d/
      - ./log/:/var/log/nginx
    command: [nginx-debug, '-g', 'daemon off;']