apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  mongodb-uri: {{ .Values.secret.mongodbUri | quote }}
  redis-uri: {{ .Values.secret.redisUri | quote }}
