version: '3.7'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    
  kafka1:
    image: wurstmeister/kafka:2.11-0.11.0.2
    restart: unless-stopped
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.108                   ## 修改:宿主机IP $ ifconfig en0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.108:9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_PORT: 9092


  kafka2:
    image: wurstmeister/kafka:2.11-0.11.0.2
    restart: unless-stopped
    container_name: kafka2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.108                ## 修改:宿主机IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.108:9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_PORT: 9093


  kafka3:
    image: wurstmeister/kafka:2.11-0.11.0.2
    restart: unless-stopped
    container_name: kafka3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.108                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.108:9094
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_ADVERTISED_PORT: 9094

  kafka-manager:
    image: sheepkiller/kafka-manager 
    restart: unless-stopped
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zoo1:2181
      TZ: CST-8               