version: '3'

services:

  mysql-db:
    image: mysql:5.7                 # 指定镜像和版本
    container_name: mysql       # 指定容器的名称
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - mysql-data:/var/lib/mysql          # 挂载数据目录
      - ./my.cnf:/etc/my.cnf      # 挂载配置文件目录
volumes:
    mysql-data: